----1:

CREATE PROC PRINTTABLE (@T INT) AS 
BEGIN 
	DECLARE @I INT = 1
	WHILE @I <= 10
	BEGIN
		PRINT CONVERT(VARCHAR(3), @T) + ' x ' + CONVERT(VARCHAR(3), @I) + ' = ' + CONVERT(VARCHAR(4), @T * @I)
		SET @I = @I + 1
	END
END

EXEC PRINTTABLE 7

--2:

CREATE PROC PRINTTABLE2 (@T INT, @X INT) AS 
BEGIN 
	DECLARE @I INT = 1
	WHILE @I <= @X
	BEGIN
		PRINT CONVERT(VARCHAR(3), @T) + ' x ' + CONVERT(VARCHAR(3), @I) + ' = ' + CONVERT(VARCHAR(4), @T * @I)		SET @I = @I + 1
	END
END

EXEC PRINTTABLE2 7, 20

--3:
CREATE PROC INSERTSTUDENT (@REGNO VARCHAR(20), @sName VARCHAR(60), @sCity VARCHAR(25), @sCGPA float, @sAge int) AS
BEGIN 
	DECLARE @SIZE INT = (SELECT COUNT(*) FROM Student WHERE regno = @REGNO)
	IF @SIZE > 0 OR @sCGPA < 0.0 OR @sCGPA > 4 OR @sAge < 18 OR @sAge > 25
		PRINT 'PROVIDE VALID DATA!'
	ELSE 
	BEGIN
		INSERT INTO Student VALUES(@REGNO, @sName, @sCity, @sCGPA, @sAge)
		PRINT 'DATA INSERTED'
	END
END
EXEC INSERTSTUDENT '21-ARID-4459', 'Attiqe', 'RWP', 3, 19


--4:

CREATE PROC INSERTENROLL (@REGNO VARCHAR(20), @cCode VARCHAR(15), @sem INT, @G CHAR(1)) AS
BEGIN
	DECLARE @SIZE INT = (SELECT COUNT(*) FROM Enrollment WHERE regno = @REGNO AND cCode = @cCode)
	DECLARE @E1 INT = (SELECT COUNT(*) FROM Student WHERE regno = @REGNO)
	DECLARE @E2 INT = (SELECT COUNT(*) FROM Course WHERE cCode = @cCode)
	IF @SIZE > 0
		PRINT 'PRIMARY KEY VIOLATION'
	ELSE IF @E1 = 0
		PRINT 'Student Doesnt Exist'
	ELSE IF @E2 = 0
		PRINT 'Invalid Course Code'
	ELSE 
		BEGIN
			INSERT INTO Enrollment VALUES(@REGNO, @cCode, @sem, @G)
			PRINT 'DATA INSERTED!!'
		END
END

EXEC INSERTENROLL '21-ARID-4453', 'CSC-101', 5, 'A';


--5
CREATE PROC PRINTCRS (@REGNO VARCHAR(20)) AS
BEGIN
	SELECT s.regno, s.sName, e.cCode, e.grade FROM Student s
	INNER JOIN Enrollment e ON s.regno = e.regno WHERE s.regno = @REGNO
END

EXEC PRINTCRS '21-ARID-4591'




	
	
