--1:
DECLARE @NAME VARCHAR(10) = 'My Name'
DECLARE @ADD VARCHAR(20) = 'Street # 4'

PRINT @NAME + ' ' + @ADD


--2
DECLARE @COUNT INT = 1
WHILE @COUNT <= 10
BEGIN
	PRINT '10 x ' + CONVERT(VARCHAR(20), @COUNT) + ' = ' + CONVERT(VARCHAR(20), 10 * @COUNT)
	SET @COUNT = @COUNT + 1
END

--3:
SELECT * FROM Student
DECLARE @YOUNGEST_AGE INT 
SET @YOUNGEST_AGE = (SELECT MIN(sAge) FROM Student)
PRINT @YOUNGEST_AGE
SELECT sName FROM Student WHERE sAge = @YOUNGEST_AGE * 5

--4:
SELECT * FROM Employee

CREATE TABLE EMP(
	eid INT PRIMARY KEY IDENTITY(1, 1),
	eage INT,
	ename VARCHAR(20)
	)
INSERT INTO EMP VALUES(24, 'Shahbaz')

SELECT * FROM EMP
DECLARE @TOTAL_EMP INT = (SELECT COUNT(*) FROM EMP)
DECLARE @MAX_AGE_ID INT = 1
DECLARE @MAX_AGE INT = (SELECT eage FROM EMP WHERE eid = 1)
DECLARE @I INT = 2
WHILE @I <= @TOTAL_EMP
	BEGIN
		DECLARE @TMP_AGE INT = (SELECT eage FROM EMP WHERE eid = @I)
		IF @MAX_AGE < @TMP_AGE
		BEGIN
			SET @MAX_AGE_ID = @I
			SET @MAX_AGE = @TMP_AGE
		END
		SET @I = @I + 1
	END
SELECT ename FROM EMP WHERE eid = @MAX_AGE_ID